org: noaoh
app: futurama-quotes-mastodon
service: futurama-quotes-mastodon

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs14.x
  environment:
    MASTODON_ACCESS_TOKEN: ${param:mastodon-access-token}
    MY_EMAIL_ADDRESS: ${param:my-email-address}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ QuotesTable, Arn ]

functions:
  mastodonHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every day at 12:00am UTC
      - schedule: cron(0 0 * * ? *)

resources: # CloudFormation template syntax from here on.
  Resources:
    QuotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: futurama_quotes 
        AttributeDefinitions:
          - AttributeName: quote 
            AttributeType: S
          - AttributeName: is_used
            AttributeType: B
          - AttributeName: quoteLength
            AttributeType: N
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id 
            KeyType: HASH 
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1